Weather records have contained valuable information concerning the pattern of tornadoes in the U.S. Spring in Texas and the U.S. heartland brings the tornado season.
Weather officials advise people to have safety plans.
Madison, Florida can attest to the fury of a tornado, having been a victim in 1988.
Fewer tornadoes occur at other times and on occasion, devastate areas beyond their usual striking zones.
1990 was such a year.
Tetsuya Fujita, a science professor in 1990, became prominent for development of a tornado measuring device and for deployment of doppler radar to enable aircraft to avoid dangerous air currents.