Political unrest and a collapsing economy prompted tens of thousands of skilled East German workers to rush through recently opened borders to West Germany.
Western leaders saw that a reunified Germany was possible.
The East bloc communists, initially opposed to the idea, softened by urging reunification as a longer-term goal, to be reached in gradual stages.
Serious concerns about the future relations of NATO and the Warsaw Pact, the impact a strong, united German state would have on the evolving European integration, trepidation by neighboring states and the fears of Jews world-wide had to be addressed.
Reunification occurred.
It was inevitable.