One F-16 fighter crashed in March 1987, two in September 1988, and two in June 1988.
One F-15 crashed in April 1994, one August-October 1990.
Two F-14s crashed in September 1988.
One F-111 and one F-4 crashed in October 1990 Three A-10s crashed in December 1988.
One B-52 bomber crashed in October 1984, one in February 1988, and one in December 1988.
Two B-1Bs crashed in November 1988.
One T-2 Buckeye trainer crashed in October 1989.
One C-5A transport crashed in August 1990.
One C-5B crashed in April 1975.
17 helicopters crashed August-October 1990.
One USAF tanker crashed in October 1988.