Domestic and foreign airlines as well as private aircraft suffered a number of air crashes during the 1960-1991 period.
Causes were terrorists, mechanical failures, pilot errors and weather.
Terrorist bombs destroyed a Boeing 747 and a DC-10 in mid-air.
A Boeing 737 crew shut down a functioning engine instead of a mal-functioning one.
The pilot of another plane accidentally flew it into a mountain.
Crashes due to weather included a Boeing 737 caught in wind shear.
A MD-82 crashed because of engine failure.
Another aircraft had multiple failures.
Loss of life and injuries brought pressure for a review of safety measures.