From 1989 to 1991, professionals and amateurs competed in marathons and half- marathons.
Competitors in the U.S. marathons came from all over the world.
Winners' prize money and times for the races varied.
Wheelchair winners could do the 26.2-mile course in less than 2 hours, with the men's and women's winners taking about 10 and 30 minutes more, respectively.
By 1989, tour companies were offering worldwide marathon vacations.
Unusual 1991 marathoners included an 83 year-old man expected to run his 60th Boston Marathon with 13,000 others and a man planning to run his marathon on the deck of a battleship.