The collapse of the Soviet Union was accompanied by major civil unrest and ethnic conflict in the former republics.
The Caucasus, Baltic and Central Asian republics all experienced unrest.
The reasons for the strife included nationalism, ethnic tensions and old grievances.
One of the most serious conflicts was in the Nagorno-Karabakh region of Azerbaijan.
The majority of the population there is Armenian and wanted unification with Armenia, Azerbaijan refused.
The conflict between the Azeris and the Armenians has existed for centuries.
Other conflicts were a direct result of the breakup of the Soviet Union.
In Moldova, the ethnic Romanian majority wanted to establish Moldova, which is close to Romanian as the official language.
The Russian minority dissented and demanded its own autonomous republic.
The Baltic republics wanted to be independent nations and many nationalities were demanding the return of lands taken from them under Stalin.
Gorbachev tried to hold the Soviet Union together through tougher legislation and by appeals for support for his reforms.
Following the collapse of the Soviet Union there was even an attempt at peacekeeping in Georgia, using Russian and Georgian troops.
There was even one call for an international peacekeeping mission in some of the hotspots.