The collapse of the Soviet Union was accompanied by major civil unrest and ethnic conflict in the former republics.
The Caucasus, Baltic and Central Asian republics all experienced unrest.
The reasons for the strife included nationalism, ethnic tensions and old grievances.
One of the most serious conflicts was in the Nagorno-Karabakh region of Azerbaijan.
The majority of the population is Armenian and wanted unification with Armenia.
The Baltic republics wanted to be independent and many nationalities were demanding the return of lands taken from them under Stalin.
In Moldova, the ethnic Romanian majority wanted to establish Moldavian as the official language.