Indiana Senator Dan Quayle, 41, George Bush's surprise choice for vice-president in 1988, was criticized as a novice.
His National Guard service and campaign gaffes were attacked.
He proved a low-profile team player and Bush announced he would be on the 1992 ticket.
Quayle's grandfather owned the newspaper in Quayle's hometown of Huntington.
Quayle, known always as a nice guy, graduated from DePauw in 1969, took National Guard training, then in 1971 worked in the Indiana Attorney General's office and for the governor.
At Indiana University Law School he met and married his wife Marilyn.
They practiced law together before Quayle spent 12 years in Congress.
They have three children.