In the aftermath of California's earthquake Tuesday, the White House reacted quickly to get federal aid flowing.
The governor of California assured victims the state also would provide aid.
Only about 25-30% of homes in the San Francisco area are said to be insured.
Insurers may have to pay billions of dollars for the earthquake but no company is expected to suffer serious financial damage.
Insurers as a whole are likely to increase the amount of reinsurance they buy which, in turn, will translate into an overall price rise, thus ending the price-cutting war between them the past two years.