A severe drought continues to affect large areas of the United States and climatologists warn that the future could see more unless steps are taken to halt the earth's rising temperature.
The drought is the worst since records began being kept in 1895 and has affected grain production across the nation.
Grain supplies are expected to fall to 17 percent of what is required to safeguard world food security.
Communities in the areas affected have restricted water use and Oregon has begun to ship hay to Kentucky.
Some areas have seen some relief as heavy storms hit large sections of the country.