The Queen of TV comedy and entrepreneur, Lucille Ball, died on April 26, 1989 at 77.
Presidents, comedians and actors, neighbors, residents of her hometown, television critics, surviving co-stars, and just plain fans paid tributes to her.
More than 2,000 attended three memorial services.
She was a chorus girl, model, and in 75 movies, but is best remembered for her physical and verbal comedy and superb timing evident on television.
She and her husband, Desi Arnaz, revolutionized television comedy with "I Love Lucy," which was filmed before a live audience, becoming a rerun gold mine, still seen world-wide.