According to a 1989 report, twelve million Americans had some form of diabetes, while yearly some 150,000 died from diabetes and another 150,000 died from diabetes-related illness.
Diabetes results from the body's failure to make insulin.
The most common form of the disease is Type II diabetes.
Hispanics were three times more likely to develop diabetes than the general population.
A study in 1988 showed that the hormone "amylin" might be responsible for causing Type II diabetes.
An anti-diabetic drug, metaforim, has been tested and, in California, programs were set up to educate Hispanics in diet and exercise.