There was a critical need for reform of the U. S. welfare system during the Reagan and Clinton administrations.
Several million families were in a poverty-dependency status, welfare consumed huge sums with no improvement, and public pressure increased.
Both presidents worked closely with the governors.
Changes focused on the need for welfare recipients to work.
The House of Representatives, however, paid lip service to reform.
The two administrations encouraged the states to initiate their own reform plans.
These included time limits on welfare checks.
Meanwhile, overseas, the capitalist nations were also having their own problems with spiraling welfare costs.