Presidents Reagan and Clinton struggled with the welfare system during the late eighties and early nineties, mandated by an indignant public.
Both agreed that the able-bodied should work for their checks, and included job-training in their proposals.
The governors were asked to experiment with welfare reforms in their states.
President Reagan's 1987 welfare proposal was criticized because only 25 percent of expenditures were earmarked for welfare-to-work provisions.
President Clinton took up welfare reform in 1993, including training and work requirements.
Internationally, other welfare states sought solutions for debt resulting from welfare, health and pension schemes which will mushroom in the future.