In 1992 and 1993, the North American Free Trade Agreement to establish free trade among the United States, Canada and Mexico was a controversial issue.
Its supporters-- the administration, business leaders and the republican establishment--spent millions of dollars.
Opponents, running a grassroots operation, included labor, many democrats, U.S. Hispanics and blacks, and ultra-conservatives.
Public support, low through September 1993, began to rise after packages were added and Vice-president Gore debated Ross Perot.
As the ratification vote grew near, both sides accelerated efforts.
Clinton's credibility and effectiveness became tied to ratification.
Following ratification, Caribbean basin nations awaited its impact.