Labor and grassroots groups argued NAFTA would send US jobs south and harm the environment.
Hispanic civil rights groups feared US Hispanic workers would suffer.
Business spent millions to support NAFTA, believing superior US productivity and products would benefit.
Rejection would increase protectionism and inflation and slow economic growth.
President Clinton made environmental and labor side agreements, including a North American Development Bank to assist NAFTA-damaged communities, and promised undecideds new projects in their districts.
A debate victory by VP Gore over Ross Perot helped swing public opinion.
After NAFTA's approval in November 1993, Central American and Caribbean governments awaited promised Caribbean-basin market protections.