Iraq, after accusing Kuwait of multiple, harmful wrongdoings, invaded and overran Kuwait.
It claimed to have responded to a request by a Kuwaiti revolutionary group.
A skeptical U.S. and U.N. rejected this justification, condemned the action, demanded withdrawal, and threatened sanctions.
The beleaguered Kuwaiti government requested U.S. military intervention.
Divided Arab nations failed to resolve the crisis.
After further Iraqi intransigence, strong U.N. economic and military sanctions were imposed, including a ban on Iraqi oil and imports.
The price of oil soared.
Iraq responded by rounding up foreigners in Kuwait, sending some to Baghdad, and alerting its citizens to a possible U.S. attack.