The Shining Path is a Peruvian Maoist group founded in 1970 by Abimael Guzman.
This group sought to overthrow Peru's elected government and install a peasant and worker state.
For 10 years is worked among the Indians in the Andes, then began guerrilla operations eventually moving into the jungles and cities.
Until Fujimori was elected president in 1990, Peruvian presidents had not been successful in handling the Shining Path, but, by 1994, many leaders of the group, including Guzman, were in jail.
A faction of free guerrillas also had formed and was beginning to assert power repudiating Guzman and his negotiations with the government.