Canadian Ben Johnson won the 100-meter dash at the 1988 Olympics but afterward tested positive for illegal steroid use.
He was stripped of his gold medal, suspended from competition for two years, and banned from Canada's team for life.
A teammate said Johnson's physician had provided steroids to her and Johnson with the knowledge of their coach.
After his suspension was over, Johnson entered a track meet in Canada where he finished second in the 50-meter dash.
In 1991, his coach testified that he had given athletes every steroid combination imaginable.
His system worked until the Johnson incident in Seoul 1988.