Ben Johnson came to Toronto from Jamaica at 14 and won a gold medal at the 1988 Seoul Olympics at 26, for his world-record 9.79-second 100-meter dash.
He forfeited medal and record when his after-race urine sample showed steroid use.
He was suspended from international competition for two years.
Johnson and his family denied any drug use.
Teammate Angella Issajenko said Dr. George Astaphan provided steroids to her and Johnson with the knowledge of coach Charlie Francis.
Francis originally suggested sabotage of the sample but in March 1989 testified Johnson had taken illegal muscle-building drugs since 1981.
Johnson testified in June 1989 that he had taken drugs for seven years and spoke out against drug use.
In September 1989 Johnson's results from 1983 to 1989 were erased, including his 9.83 in the 100 meters at the 1987 World Championships in Rome, under the IAAF's new Ben Johnson Rule which allowed it to decertify results if athletes were later shown to have used a banned substance before performances.
A smaller Johnson, still 174 pounds and bench-pressing 365, returned to competition in The Hamilton Spectator Indoor Games in January 1991 and came in second.
Johnson was receiving high appearance fees and giving interviews only for pay.