At the Seoul Olympics in September 1988, Canadian Ben Johnson won the 100-meter dash but was stripped of his gold medal, suspended from international competition for two years, and banned from Canada's team for life after testing positive for illegal steroid use.
A fellow Canadian sprinter, in a published interview, said that Johnson's personal physician had provided steroids to her and Johnson with the knowledge of their tract coach.
The physician denied he had ever prescribed such drugs to any athletes.
In June 1989, Johnson testified that he had used illegal performance-enhancing drugs in 1987.
An employee of NBC-TV and physical therapist at the Seoul Olympics, said that Johnson's track coach remarked before the race that Johnson is "more afraid of failing the drug test that he is of Carl Lewis."
After Johnson's two-year suspension ended in September 1990, track meet promoters eagerly signed him up to race in Hamilton, Canada.
He finished second in the 50-meter dash, far off his record time, but received a standing ovation.
In 1991, his Canadian coach testified at a federal inquiry that he had given athletes every steroid combination imaginable.
His system worked well until Johnson was caught for illegal steroid use at Seoul.