Jamaican-born Ben Johnson, 26, won a gold medal for Canada at the 1988 Seoul Olympics for his world-record 9.79-second 100-meter dash.
He forfeited medal and record and was suspended from competition when tests showed steroid use.
Johnson's 9.83 record in the 1987 World Championships was erased under the new Ben Johnson Rule, allowing decertification of results later shown to be achieved under drugs.
Johnson denied drug use but later admitted it after teammate Angella Issajenko said Dr. George Astaphan provided them with steroids and coach Charlie Francis testified Johnson had taken drugs since 1981.
Johnson returned to competition in January 1991, placing second.