America's maestro, Leonard Bernstein died at 72 on October 14.
Suffering from lung diseases since spring, he announced his retirement four days earlier.
"Lenny" was the first American conductor to attain world fame.
He composed both classical and popular music and introduced thousands to classical music on television.
He made more than 200 classical recordings, many now being examined for re-release.
Posthumous plaudits have come from everywhere, with memorial classical concerts in New York and Los Angles, as well as a goodbye from Broadway.
His 70th birthday celebrations had featured all-star fundraising concerts at the Tanglewood Music Center and Carnegie Hall.