Many Americans believe that career Washington politicians are mostly concerned with their self-preservation.
During the prior three elections 96% or more of House incumbents who ran for reelection won.
Furthermore, their perks and privileges make challenging them futile.
A solution to this problem is term limits.
However, some political scientists believe term limits is a cure that's worse than the disease and may be unconstitutional.
Still others think the fundamental problem is not incumbency, but rather the tenured, seniority committee system, which leads to entrenched arrogance, greater special interest fund raising and attention.
Perhaps the term limits should only be on committee assignments.