In the early 1990s, an argument on the merits of term limits arose nationwide.
Several states put the issue to referendum and the question also emerged at the national level.
A CBS-Gallup Poll showed that Americans favored term limits regardless of age, gender, party or ideology.
Proponents of limits cited the high rate of incumbent reelection, creating life-long legislators who became arrogant and unresponsive to constituents' issues.
Another result mentioned was a dearth of minorities in legislatures and Congress.
Opponents cited the loss of experience and control over special interest and lobbying groups and the weakening of legislative power, among other issues.