In the early 1990's, term limitations for elected officials, especially legislators, was a popular issue.
According to polls, 75% of Americans backed limits.
It was hard to unseat an incumbent and term limits were viewed as constitutional and a way to end political careerism and take power away from special interest groups.
Others believed amateurism would result and increase the power of the special interest groups, unelected staffers, and executive department bureaucrats.
Limits, not supported by the nation's founders, would restrict the voter's choice and throw out the good officeholders with the bad.
Some pundits suggested less radical solutions.