From 1987 to 1993, hunger was endemic in much of the world with one billion people living on less than $1 a day.
The Third World debt was huge and had untenable debt service fees.
Although some blamed the Third World governments, developed nations were asked to cancel or reschedule debts and increase financial aid.
In 1987, some small U.S. banks were writing off loans.
The World Bank was expected to take the lead and gradually moved from being a development institution to one with programs that were directed at easing poverty and helping the environment.
Privately administered micro- enterprise lending had some success.