The World Bank has not been successful in reducing Third World debt.
There are many differing views on how to accomplish this, from adhering to the bank's policies to writing off these debts as uncollectible.
A persistent problem in loaning money by the World Bank is that Third World countries are often overwhelmed with interest payments.
World Bank officials will not make a commitment on specific measures for Third World debt reduction.
Some individual initiatives for alleviating Third World debt and poverty are promising in that they are directed at human resources and are not commercial arrangements.