On Monday President Bush and the USS Iowa commander attended a memorial at Norfolk Naval Air Station for 47 sailors that were killed in an explosion of the battleship's No.
2 gun turret last Wednesday.
The Iowa, a WW II battleship returned to duty in 1982, was conducting firing exercises near Puerto Rico at the time.
The Defense Department said the blast possibly originated with a gunpowder bag used to fire the one-ton shells.
Eleven people inside the turret, all on the lowest deck loading powder, survived.
The Navy is investigating the accident.
Firings of the 16-inch guns have been suspended.