Overloading is a major contributor to ferry and passenger boat accidents, particularly in the third world.
Ferries in India, Guatemala, Egypt, China and Bangladesh all carried for more passengers than authorized, when they sank.
Many deaths more passenger occur to those below decks than to those above.
Captain error also contributed to accidents.
Other accidents have involved poor weather and in one case in Bangladesh, river pirates.
But even advanced countries have ferry accidents.
Nineteen U.S. sailors died when an Israeli ferry sank while returning the sailors to the USS Saratoga.
No cause for the accident was reported.