Overloading is a major contributor to ferry and passenger boat accidents, particularly in the third world.
Ferries in India, Guatemala, Egypt, China and Bangladesh all carried far more passengers than authorized when they sank.
Captain error also contributed to accidents.
In Guatemala, a ferry captain was charges with negligent homicide when his boat which was being towed, sank after he failed to steer it.
A ferry sank off the Egyptian coast after inexplicably leaving standard navigational channels and ramming a coral reef in stormy seas.
In that accident, survivors claimed that crewmembers abandoned ship without helping them.
The ship's engineer denied the charges.
Two boats carrying Somali refugees sank off the coast of Kenya, resulting in more than 140 deaths, although the cause of the sinking was not reported.
An overcrowded ferry in Bangladesh sank with almost double the passengers it was authorized.
In a separate ferry incident in Bangladesh, pirates robbed passengers and threw six overboard.
In the Indian accident, monsoon rains may have contributed as well as overcrowding.
Even an advanced country such as Israel can experience ferry accidents.
Nineteen U.S. sailors died when an Israeli ferry sank while returning the sailors to the USS Saratoga.
No cause was reported.