The nation's police forces were in trouble in the late 1980s-early 1990s with charges of racism, brutality, and false arrest leveled against them.
Typical was the Los Angeles Police Department (LAPD) that had to suffer through a false arrest charge when one of its officers arrested a retired major league baseball star; also when it had to endure the disgrace of the Rodney King beating.
Investigations followed, and much blame was put on its chief, Daryl Gates.
The LAPD did not do any better in handling anti-abortion demonstrators.
They began twisting arms, etc.
One police chief attributed the cause in part to a police chiefs' code of silence concerning police abuse.
Even the Los Angeles County Sheriff's Department succumbed to police violence with shootings and even a robbery.
In other cities, the Long Beach Police was involved in a sting operation when one of its officers was caught on videotape pushing an undercover black policeman through a plate glass window.
Police forces in Chicago, Minneapolis, Kansas City Missouri, and Santa Clara were also involved in cases of racism and brutality against minorities.
To make matters worse, the Ventura County district attorney's office refused to prosecute suspects who claimed police brutality.