The nation's police forces were in great difficulty in the late 1980s-early 1990s with charges of racism, brutality and false arrest leveled against them.
The Los Angeles Police Department was prominent in these charges, having to endure such publicized events as the videotaped Rodney King beating.
There were investigations and on several occasions, police chiefs were to blame, some even encouraging such police actions and others remaining silent.
Police racism and brutality against minorities was prevalent.
One county district attorney's office refused to prosecute suspects who claimed police brutality, believing that it could not win such cases.