The subject of police brutality and racism received national attention following the airing of the videotaped beating of Rodney King by four Los Angeles Policemen back in March.
Los Angeles is not the only city faced with claims of police brutality.
In Long Beach, a white policeman was secretly filmed while he pushed an off-duty black policeman through a plate-glass window.
Over the past two years, in Ventura County, the district attorney's office dropped charges against four suspects who contended that they were victims of police brutality.
Other cities struggling with police brutality include Chicago, Kansas City, and Minneapolis.