The subject of police brutality received national attention following the airing of the videotaped beating of Rodney King by four Los Angeles Policemen back in March.
A commission appointed by Mayor Tom Bradley and Police Chief Daryl Gates in the wake of the videotaped beating was issued yesterday.
The commission found that a significant number of officers use excessive force against Los Angeles residents.
In-mid June, a lawsuit against the Los Angeles Police Department was settled when police agreed to stop using a martial-arts weapon, nunchakus, against anti-abortion advocates.
Los Angeles is not the only city faced with claims of police brutality.
In Chicago, blacks accused officers of unprovoked beatings and false arrests.
In Minneapolis, in January, allegations of police racism and brutality shook the city following the deaths of two blacks at a drug raid that went awry.
In Long Beach, California, a white policeman who was secretly filmed while he pushed an off-duty black policeman through a plate-glass window.
While in Kansas City, in June, several white officers bloodied a Nigerian-born Roman Catholic priest with nightsticks as he lay on the ground.
Finally, over the past two years, in Ventura County, California district attorney's office dropped charges against four suspects who contended that they were victims of police brutality.