Five children were slain in the schoolyard of Cleveland Elementary School on Tuesday, the victim of a drifter with a troubled past.
Patrick Edward Purdy, armed with an AK-47 and a pistol, entered the crowded schoolyard just before noon and opened fire.
When the shooting was over, five students lay dead and 29 others, as well as one teacher, were wounded.
Purdy lay dead of a self-inflicted gunshot wound to the head.
Cleveland Elementary School is two-thirds Asian and the five students, one Vietnamese and four Cambodian, as well as 19 of the wounded were all Asian.