An abnormal protein (prion) that eats holes in the brain causes spongiform encephalopathy (SE) diseases.
Since the 1700's, one SE disease (scrapies) attacked British sheep.
Cattle that ate feed containing sheep by-products began dying from "mad cow disease" in 1986.
By 1990, the British beef industry was under siege, with several nations imposing import restrictions and domestic consumption down.
By 1994 more than 120,00 cattle and a few other animals had died in the UK from "mad cow" and the European Union was considering import bans.
Researchers were looking for a causal relationship between "mad cow disease" and SE diseases that rarely afflict man.