The mountainous area of northern Iran was rocked by an earthquake measuring between 7.3 and 7.7 on the Richter scale early Thursday morning.
Killing as many as 55,000 people and injuring thousands of others, the earthquake occurred as most people were asleep.
The United States will be providing $300,000 in supplies through the American Red Cross and other U.S. agencies.
Iran, which broke diplomatic ties with the U.S. in 1979, has welcomed the aid.
Russia has begun to airlift supplies into the area and is sending a rescue team from Soviet Armenia, the site of a devastating 1988 earthquake.