The North American free trade agreement between the US, Canada and Mexico faced strong opposition from labor, grassroots groups, and billionaire Ross Perot's presidential campaign.
Opponents argued NAFTA would send US jobs to Mexico and harm the environment.
Hispanic business organizations backed NAFTA but civil rights groups feared US Hispanic workers would suffer, and insisted on protective agreements for worker rights and the environment.
The business community spent millions in support of NAFTA.
Investors believed NAFTA would benefit superior US productivity and products.
Rejection would increase protectionism and inflation and slow world economic growth.
President Clinton supported NAFTA after reaching environmental and labor-issue side agreements, like a North American Development Bank to assist NAFTA-damaged communities.
He chose strategically connected William Daley to build NAFTA support in Congress and bought off undecideds with promises of new projects in their districts.
Former Presidents Carter, Bush and Ford spoke in NAFTA's support.
Public opinion was anti-NAFTA in September 1993 but reversed after a debate victory by Vice President Gore over Ross Perot.
Four days before the House vote the outcome was too close to call.
After NAFTA's approval, Central American and Caribbean governments fearing a more competitive Mexico awaited word on Clinton's promised Caribbean-basin market protections.