Clarence Thomas, a black conservative republican, was confirmed as a Supreme Court justice on 16 October 1991.
Born in poverty in Pinpoint, Georgia in 1948, he was raised by grandparents and sent to catholic school.
He completed Holy Cross College in 1971 and Yale Law School in 1974.
Thomas then changed from liberal to conservative.
He held several positions in civil rights and equal employment opportunity.
He was appointed a judge of the U.S.
Circuit Court of Appeals in 1990.
One journalist thought he was helped by affirmative action.
His mother did not believe a sexual harassment charge against her son.