Lawsuits are being filed in the U.S. District Court in Pittsburgh to prevent the Census Bureau from counting illegal aliens.
The Census Bureau counts all residents every 10 years to reapportion a total of 435 seats in Congress.
Groups wanting to ignore illegal aliens believe that large concentrations of them could result in some states gaining seats in the House of Representatives at the expense of other states.
The Census Bureau contends that efforts to identify illegal aliens could delay and complicate the count.
Despite lawsuits and the Senate's vote to stop the count of illegal aliens, ultimately the Supreme Court may have to make the final decision.