Congress is debating whether or not to count illegal aliens in the 1990 census.
Congressional House seats are apportioned to the states and huge sums of federal money are allocated based on census population.
California, with an estimated half of all illegal aliens, will be greatly affected.
Those arguing for inclusion say that the Constitution does not mention "citizens", but rather, instructs that House apportionment be based on the "whole number of persons" residing in the various states.
Those opposed say that the framers were unaware of this issue.
"Illegal aliens" did not exist in the U.S. until restrictive immigration laws were passed in 1875.