Forty members of the House of Representatives along with the Federation for American Immigration Reform will take part in a lawsuit that will be filed in the U.S. District Court in Pittsburgh.
The groups will sue the Census Bureau in an effort to force the agency to delete illegal aliens for the 1990 census count.
Traditionally, the Census Bureau counts everyone living in the Country.
That count is used to reapportion a total of 435 seats in Congress.
Groups wanting to ignore the illegal aliens believe that large concentrations of them could result in some states gaining seats in the House of Representatives at the expense of other states.
The Census Bureau contends that the effort to identify illegal aliens could delay and complicate the count and in effect invalidate it.
In addition, identifying illegal aliens for the count may be a difficult thing to do.
Generally speaking a person who is in the country illegally does not want to be spotted by the government.
The Constitution requires that all residents be counted every 10 years for reapportionment purposes.
Even though the Senate has voted to stop the count of illegal aliens while others are filing lawsuits in Pittsburgh to prevent their count, ultimately the Supreme Court may have to make the final decision.