The Big Mac debuted to mixed review as McDonald's opened restaurants in Korea, Yugoslavia, the Soviet Union, and China.
Large crowds stood in line for hours at openings in Belgrade, Moscow, and Peking.
Customers in Yugoslavia, the first communist country to get a McDonald's, and China raved about the taste of the Big Mac.
In Moscow, the Russians were less enthusiastic about its taste but gave a thumbs up to the shakes.
The openings came after long negotiations which, in most cases, saw McDonald's contracting with local farmers for the beef, potatoes and other supplies needed for its restaurants.