Emperor Hirohito of Japan died in 1989 at the age of 87.
He ascended to the throne in 1926 and presided over one of Japan's most tumultuous eras.
The last of the World War II generation of leaders, Hirohito was a controversial figure, even in death.
While many western leaders praised him, many Asian leaders, whose countries suffered under the Japanese military during World War II were cool.
While most historians believe that Hirohito was a powerless figurehead, others believe that he had to have known of the massacre of thousands of Chinese in Nanking and of the plan to bomb Pearl Harbor.
Some believe that the U.S. covered up his complicity in war crimes after the war to avoid unrest in Japan.
After the U.S. dropped the atomic bomb on Japan, Hirohito announced Japan's surrender in a radio address to his nation.
After the war, Hirohito was just a symbol but the imperial system has remained important to the Japanese people.
Hirohito had traveled in Europe and had a preference for Western food and clothes.
With few real responsibilities, he spent much time in the study of marine biology.
He died of cancer after a long illness and is succeeded by his son Akihito.