Japan's Emperor Hirohito, posthumously named Showa, left a $13 million taxable estate.
He died of cancer on Jan. 7.
Hirohito is remembered for surrendering in WW II.
Though many world leaders mourned his passing, South Korea and others viewed him as a symbol of Japanese crimes against Asian people.
Generally portrayed as a peaceful man, a January BBC documentary claims that Truman decided not to prosecute Hirohito for war crimes, and that Japan's wartime prime minister was pressured into changing his testimony to avoid incriminating the emperor.
An LA newspaper published a letter to the editor after Hirohito's death also questioning his innocence.