Super Bowl XXIV gave the 49ers their fourth Vince Lombardi Trophy.
Sixty-three percent of TV viewers watched the lopsided game which also featured the conclusion of the "Bud Bowl II," a $7 million Anheuser Bush ad campaign.
Though the game can spotlight a community's problems, it also has tremendous economic impact.
Communities such as Los Angeles--Orange County, therefore, offer incentives, such as rent-free stadium use, to lure the game to their city.
Even with tougher business entertainment tax laws, companies are well represented at the event.
Traditionally, the winning Super Bowl team is invited to the White House.