Philippine President Corazon Aquino's administration was beset with problems from June 1988 to October 1990.
Ferdinand Marcos plagued the earlier years.
Swiss bankers required a criminal prosecution to release information on his funds.
His wife, Imelda, and his supporters wanted him to be allowed to die, or at least be buried, in his homeland.
Her agrarian reform policy suffered a number of setbacks.
Economic problems were the focus of her 1989 European trip.
Six military coups and many military mutinies against her government occurred.
Communist insurgents continued their 21-year campaign.
In April 1990, she was willing to negotiate with the insurgents and renegade military.