In 1988 economic decline was increasing Slovenian-Serbian friction.
In June 1990 a new government in Slovenia planned for Slovenian sovereignty within a Yugoslav confederation.
In June 1991 fighting followed Serbian president Milosevic's blocking of a Croatian federal president, and an EC-brokered cease-fire called for a three-month delay in independence moves.
More fighting followed Slovenia's June 25th secession.
Slovenia sought to become a market-oriented parliamentary democracy and worked to establish new foreign credit and replace markets lost in Yugoslavia.
By March 1993 privatization had begun.
In 1994 Slovenia approached Belgrade regarding normalization of relations, but Serbia remained distrustful.