In 1988 Slovenian-Serbian friction was increasing and in 1990 Slovenia proposed sovereignty within a Yugoslav confederation.
Fighting surrounded its June 25, 1991 secession.
Afterward, Slovenia sought to become a market-oriented democracy and replace lost Yugoslav markets.
By 1993 privatization had begun.
In 1994 Slovenia approached Belgrade regarding normalizing relations but Serbia remained distrustful.