In June 1988, the Reagan administration moved to deal with a drought plaguing most of the nation by appointing an interagency group, monitoring the situation, and issuing activity reports.
By mid-July, the drought had shifted from the Rockies to the Mid-Atlantic, affecting 29% of the nation.
President Reagan signed a $3.9 billion relief program that eventually, due partly to lax rules, became a windfall for thousands of farmers who received cash for normal trials of nature.
Nevertheless, the aid did reach to most needy areas, especially North Dakota.
Crop yields plummeted but commodity prices rose and farm solvency still improved.