New treatments are contributing to fewer deaths from heart attacks over the past decade.
Drugs, surgery, and tests to determine risk all show promise.
Taking aspirin can cut heart attack risk in half, but can increase the risk of hemorrhagic stroke in some people.
Post- heart drugs dissolve clots and limit the damage to cardiac cells reducing the risk of a subsequent heart attack.
Angioplasty may be needed for fewer heart attack victims with the use of these drugs.
Surgery bypassing one-third of the lower intestine lowers cholesterol and tests to determine levels of a blood protein can identify those at risk for a heart attack.