On August 2nd, 1990, 100,000 Iraqi troops massing on Kuwait's border crossed over, occupying the country and destroying all government buildings and installations except for the water system and oil equipment.
Over 200 Kuwaitis were killed or wounded.
Iraq facilitated residents' departures then trucked in Iraqis to replace Kuwaitis and change the population's make-up.
Thousands fled to Saudi Arabia, including the leadership.
Jordan also took in refugees.
Saddam Hussain accused Kuwait of exceeding OPEC production quotas to drive down prices, and stealing oil from Iraqi border wells.
Iraq claimed it invaded at the request of Kuwaiti revolutionaries who staged a coup, which Kuwait denied.
Kuwait said Iraq invaded because it demanded Iraq pay back billions loaned during the 1980-1988 Iran- Iraq War.
Iran rejoiced that the world was waking up to Saddam Hussein.
Kuwait appealed for US and UN help.
Bush said the US would take any action necessary to defend its Persian Gulf interests and diverted a naval group to the Gulf.
The US, UN, and EEC imposed trade and military sanctions against Iraq and Kuwait, supported widely by other countries.
The Soviets and China stopped Iraqi arms sales.
Iraq rounded up Westerners in Kuwait and threatened to hold hostage citizens of countries imposing sanctions.
Oil prices hit five-year highs.