On August 2nd, 1990, Iraq occupied Kuwait with 100,000 troops, destroying government buildings and installations, killing 200, and replacing fleeing Kuwaitis with Iraqis.
Saddam Hussain accused Kuwait of overproducing to drive down oil prices and stealing oil from Iraqi border wells.
Iraq claimed it invaded at revolutionaries' request.
Kuwait said Iraq invaded because Kuwait pressed for war loan repayment.
Kuwait appealed for US and UN help.
Bush pledged to defend its Persian Gulf interests and sent a naval group.
The US, UN, and EEC imposed widely-supported trade and military sanctions against Iraq and Kuwait.
Iraq threatened to hold citizens of sanction-imposing countries hostage.
Oil prices soared.