The longest, costliest, criminal trial in American history, the McMartin Pre-School molestation case, ended Thursday without finding Raymond Buckey or his mother, Peggy McMartin Buckey, guilty.
The California case began in 1983 and became a frenetic, media-fed, witch-hunt.
Reactions to the verdict included tears, no surprise, disappointment, anger, excuses, and finger pointing.
Jurors criticized elements of the case and said some of the children may have been molested, but the prosecution failed to prove the defendants responsible.
Other parties defended their own roles, but blamed others or the system.
Reverberations will continue in civil courts, bookstores, and on television.