The major earthquake that struck the San Francisco Bay area Tuesday occurred in a region seismologists targeted as having the highest probability of a strong quake in Northern California.
If experts could pinpoint when and where earthquakes would occur, thousands of lives could be saved.
Two of the most deadly earthquakes ever recorded occurred in Armenia and China.
The Armenian quake that killed 25,00 people pushed last year's earthquake-related death toll worldwide to the highest level since 1976 when a Chinese earthquake killed at least 10 times as many.
The annual death toll for earthquakes is about 10,000.