Lucille Ball, who died in April 1989 at the age of 77, will long be remembered.
She made her craft look easy, spontaneous and unrehearsed.
The result was the durable and probably the finest series in television history, "I Love Lucy".
She starred with her husband, Desi Arnaz, in the '50s show and together they founded Desilu Productions, which eventually took over RKO Studios.
She was an astute businesswoman as well as a talented entertainer and Desilu produced some of the most popular programs of the '50s and '60s.
Ball and Arnaz divorced in 1960.
They had two children.
At her death there was an outpouring of sympathy from the very famous to thousands of her ordinary fans.
She was particularly remembered in her hometown of Jamestown New York where she had contributed to local charities, civic events and Jamestown Community College.
Following the breakup of her first marriage, she married Gary Morton, her husband at her death.
Miss Ball had a successful career before television, starring in 75 films.
She died in Los Angeles, following emergency heart surgery.
William Paley, Chairman of CBS said that she helped to establish television as the nation's leading entertainment industry and that her legacy would last forever.