On April 24, 1990, shuttle Discovery carried the 12.5-ton Hubble Space Telescope 380 miles into space.
Orbiting above Earth's distorting atmosphere, Hubble would see 10 times better than the largest Earth telescopes.
Technical problems exacerbated by conservative system settings put Hubble several days behind schedule.
Discovery's five astronauts were all veterans of previous flights.
Discovery followed Hubble for two days to assist if necessary.
Spacelab Astro was to be put up two weeks later to give additional target information.
Hubble cost $1.5 billion, with millions more projected for support over its 15-year lifetime.
Discovery carried a telescope eyepiece used by Edwin Hubble, for whom the Hubble is named.