Nelson Mandela, the leading opponent of South Africa's white-led government was freed after 27 years in prison on 11 February 1990.
From prison he had led the fight against the government's policy of racial segregation, apartheid.
He was convicted in 1964 of conspiracy to overthrow the government and sentenced to life in prison.
International pressure had been mounting for his release and many governments had imposed sanctions on South Africa.
He continued the fight for black human rights after his release, but had many problems to overcome including factional fighting between the ANC and the Zulu Inkatha group.