Nelson Mandela, the leading opponent of South Africa's white-led government was freed after 27 years in prison on 11 February 1990.
From prison he had led the fight against the government's policy of racial segregation, apartheid.
He, along with other members of the African National Congress, was convicted in 1964 of conspiracy to overthrow the government.
Over the years, international pressure had been mounting for his release and several governments had barred imports from South Africa or investments in the country.
Upon his release Mandela continued the fight for black human rights, but he faced many problems.
He attempted to negotiate an end to the violence between the ANC and the Zulu Inkatha group, which had resulted in many deaths in the Black townships.
His wife was convicted of kidnapping and sentenced to 6 years in prison.
Nelson joined the ANC when he was 26 and rose to a leadership position.
The ANC was outlawed in 1960.
He was sentenced to five years in prison in 1962 for illegally leaving the country and for organizing a strike.
Mandela was highly praised during a visit to the United States after his release, but Jewish groups were critical of his support for the Palestine Liberation Organization.