Solar eclipses occur somewhere on earth twice a year.
Fewer than a third of them are total.
On July 11, 1991, a spectacular total eclipse, 165 miles wide, swept from Hawaii, through the southern Baja Peninsula and into central Brazil.
Officials in Baja and Hawaii, although welcoming the economic boost of tourism, were concerned that their infrastructure was not adequate to handle the expected spectator onslaught.
Permanent eye damage can result if viewers do not watch eclipses through a protective device such as special Mylar glasses, welder's masks or a "pinhole camera".
Cloud cover obscured viewing conditions at most locations.