On 24 March 1989, the oil tanker Exxon Valdez ran aground on a reef near Valdez, Alaska, spilling 8.4 million gallons of crude oil into Prince William Sound.
In two days, the oil spread over 100 miles with a heavy toll on wildlife.
Cleanup proceeded at a slow pace, and a plan for cleaning 364 miles of Alaskan coastline was released.
In June, the tanker was refloated.
By early 1990, only 5 to 9 percent of spilled oil was recovered.
A federal jury indicted Exxon on five criminal charges and the Valdez skipper was guilty of negligent discharge of oil.