On 24 March 1989, the oil tanker Exxon Valdez ran aground on a reef about 25 miles from Valdez, Alaska, spilling over 8.4 million gallons of crude oil into Prince William Sound.
Exxon stated that the captain was not on the bridge when the accident occurred and the third mate in command did not have a proper pilot's license.
Both men and a helmsman were relieved of duty.
The critical cleanup effort was slow and ineffective and the size of the spill, plus the fact that it was in such a productive area, prompted complaints from residents and environmentalists.
Within two days, the oil had spread over 100 miles and the toll on wildlife was mounting.
In May, Exxon officials released a revised plan for cleaning 364 miles of Alaskan coastline.
In June, the tanker was successfully refloated.
By early 1990, the worst was over but Exxon's total cleanup costs were $1.38 billion, only 5 to 9 percent of spilled oil was recovered, and thousands of animals had died.
In February, a federal grand jury indicted Exxon on five criminal counts.
In March, a jury found the Valdez skipper guilty of negligent discharge of oil but innocent of more serious charges.