On March 24, 1989, the Exxon Valdez ran aground in Prince William Sound, Alaska, and spilled 11.3 million gallons of crude oil.
By April, a disaster area was declared, the herring season was cancelled, an investigation of rising gasoline prices was called for, a boycott of Exxon was begun, and the slick covered an area the size of Delaware.
Clean- up operations stopped on September 15, with 117 miles of beach still oily.
In early 1990, Exxon announced a drop in earnings and an almost $2 billion spill price tag.
The cleanup was to resume on May 1.