Marathons are an experience of success, failure, and excitement.
Such is the Boston Marathon with its storied past.
This race often turns into a speed duel.
Ethiopians have dominated U.S. marathons in the past and appear ready to do it again.
Patience is an asset in marathon running.
Foreigners have prevailed in U.S. marathons, as they did in the 1990 New York City Marathon.
In addition to patience, stamina and determination are almost necessary requirements for the successful marathon runner.
For marathon enthusiasts, "marathon vacations" are now available for those who want to mix a marathon with a vacation.