The 1991 Boston Marathon expected 13,000 runners (purse $55,000).
The 1989 Long Beach Marathon (purse $9,500), with 4,021 runners, included the Pacific Rim Marathon of invited country-teams.
Chicago's marathon has the world's richest purses ($50,000, $30,000, $20,000).
3,056 runners entered the 1989 San Diego International Marathon (purses $5,000, $2,500, $1,500.)
Other marathons are run in Bangkok, Belgrade, Berlin, Bermuda, Boulder, Brussels, Budapest, Houston, Iceland, London, Moscow, Munich, Nebraska, New York City, Paris, Portland, Rome, Rotterdam, San Diego, San Francisco, Seoul, Stockholm, Tel Aviv, the Twin Cities, Venice, Vienna, and Washington, DC (Marine Corps Marathon).
Other marathons are Commonwealth Games, Goodwill Games, Olympics, and World Cup.