Robert Maxwell has been described as the Citizen Kane of his time.
The mysterious death of this larger than life individual on November 5 has left the economic affairs of Maxwell Communications Corporation and Mirror Group Newspapers is a state of confusion.
Maxwell was born in Czechoslovakia and immigrated to Britain in 1940 to escape the Holocaust.
He put together and personally ran world-wide publishing empire that included Macmillan Publishing House in New York, Britain's Daily mirror, the Daily Record and the European and British Printing Company, and communications Corp., Britain's largest printing company.
Improprieties have been alleged in the handling of funds which involve not only Robert Maxwell, but two of his sons, Kevin and Ian, as well as Michael Stoney, an executive in several Maxwell companies.
At issue is the alleged improper transfer of funds in an attempt to handle his publishing empire's crushing debts.
Among the interests named in the transfer of funds to two Swiss trusts, is the U.S. investment firm Goldman Sachs.
Maxwell also is accused of using MCC in an effort to raise funds by making late payments on the foreign market.
In doing so, MCC in effect gave itself an unauthorized loan.