In October 1989, after being hospitalized for kidney surgery, former East German leader Erich Honecker--along with other Party officials--was arrested and imprisoned to await trial for treason and corruption.
Judged too ill from imprisonment, he was placed in a Soviet East Berlin hospital.
He also faced a murder charge about his role in killing people trying to escape from East Berlin.
In 1992, Honecker took refuge in the Chilean Embassy in Moscow but was soon ordered to leave.
In Germany, he was tried, imprisoned and released in 1993.
He died in Santiago, Chile in 1994 at age 81.