Poverty is a near universal condition in much of the world.
One billion people live on less than one dollar a day.
In 1992, World Bank president Lewis Preston issued a directive to link loan volume to the strength of a country's efforts to fight poverty.
This initiative forms part of a new drive to make poverty alleviation the bank's central mission in the 1990's.
John Hatch, founder of the non-profit Foundation for International Community Assistance developed a concept of using small revolving loans to poor women to finance their private enterprise.
The interest rate would be between 1 percent to 3 percent.