The De Beers cartel, controlled by the Oppenheimer family, controls 80% of the uncut diamond market through its Central Selling Organization.
The cartel has kept the diamond market stable by maintaining a buffer pool of diamonds for matching supply to demand.
De Beers opened a new mine in 1992 and extended the life of two others through underground mining.
Innovations have included automated processing and bussing workers in daily from their homes.
African nations have recently demanded better terms.
After the Soviet breakup, De Beers contracted for diamonds with the Yukutian Republic.
The US remains the largest diamond market, followed by Japan.