Damage caused by Hurricane Andrew could reach $20 billion, making it the costliest storm this century.
The greatest toll was in south Florida, particularly in the town of Homestead, which was largely flattened.
Less damage occurred in Louisiana.
Even though much of the loss was not insured, payments for this storm could total $7.3 billion, which coupled with $3.9 billion of prior industry losses, will make this the costliest year in US property-casualty industry history.
Foreign reinsurance companies carry little of the loss.
President Bush, after a poor initial start, has intensified efforts to bring aid to those affected.