The British and French were tunneling under the English Channel by October 1988.
The object was to connect the two nations via a "Chunnel" to be completed in 1993-94.
The British public was not an eager partner in the enterprise--they liked their old island status.
France pushed ahead, hoping to improve the economy of northern France.
The tunnel became the center of Europe's attention for its size and economic promise, in spite of its cost factor.
Property values on both sides were starting to recover.
The Belgians as well as the French expected improved economic conditions.