British and French workers were expected to complete the 31-mile "chunnel" between England and France by May 1994.
It would cut the London-Paris journey from six hours to three and reinforce trade.
Initially, the English showed that they did not want a fixed link, fearing rabies, rats and terrorists coming through.
In rural SE England, they were reluctant to have high-speed trains screaming through.
The French viewed the chunnel positively, expecting it to revitalize its depressed northern regions where the tunnel surfaces and as buyers and entrepreneurs set up bases on the Continent, and holidaymakers and freight traffic heads for the tunnel.