John Lennon spirit is still very much alive to adoring fans worldwide ten years after his death.
His 50th birthday was observed with a global celebration of his peace anthem "Imagine" which was played for an estimated 1 billion people in 130 countries.
The song was played following a brief ceremony at the United Nations.
Fans also gathered in Liverpool, Moscow, Los Angles and New York to pay tribute to the former Beatle.
One biographer described Lennon as an anorexic bisexual addled by drugs who raged his way from Liverpool to New York, but friends and family denounced that version of Lennon's life.
Lennon himself acknowledged his drug use and sexual promiscuity, although he claimed that his worst days were behind him.
His wife, Yoko Ono admitted using heroin for a time.
He had also been portrayed as a dour, shoeless youth with an unfit mother, a description refuted by his half-sister in her book.
Since his death, his wife has kept his legacy alive, issuing new albums of his work and selling memorabilia, featuring his image.
Lennon was gunned down by a deranged fan outside his Manhattan apartment December 8, 1980 at the age of 40.