John Lennon's spirit is still very much alive to adoring fans worldwide ten years after his death.
His 50th birthday was observed with a global celebration of his peace anthem "Imagine" which was played for an estimated 1 billion people in 130 countries.
The song was played following a brief ceremony at the United Nations.
One biographer described Lennon as an anorexic bisexual addled by drugs who raged his way from Liverpool to New York Family and friends have denounced the book.
Lennon was ginned down outside his Manhattan apartment in December 1980 by a deranged fan at the age of 40.