The Second Amendment concerns the right to "--keep and bear arms."
The interpretation of this amendment determines the success or lack of success of effective gun control legislation.
The National Rifle Association (NRA) leads the pro-gun lobby.
The NRA interprets the Second Amendment as guaranteeing the right of the individual "--to keep and bear arms."
Gun control advocates interpret the Second Amendment in the light of its 1792 context, i.e., it is neither a legal basis for gun ownership nor for non- registration.
Public opinion appears to be turning toward a more favorable view of the need for gun control.