The 1988 fires in the greater Yellowstone ecosystem were the worst in a hundred years, burning nearly 1.5 million acres.
The House Agriculture Committee has planned hearings into how the Forest Service handled the wildfires.
The Interior Department ordered a moratorium on its "let- burn"'policy.
New studies showed unseen smoke hazards faced by firefighters.
Firefighters battled hundreds of blazes in five Western states in 1989.
California was geared up for a dangerous wildfire season in 1991.
Residents in Santa Barbara were advised on fire- resistant landscaping (e.g., firescaping and xeriscaping) and potential firestorm problem areas around San Francisco Bay were identified.