Foresters say the heavy rains that have pelted California in the past two weeks have worsened the threat of fierce forest fires this summer because they will stimulate the growth of grasses that later dry and become fuel for wildfires.
In 1988 drought conditions and high winds help make it the worst year in hundreds of years for wildfires.
The U.S. Forest service said 5 million acres were charred in the raging blazes, 706,000 acres in Yellowstone National Park.
As this summer's wildfire season approaches, firefighters are wondering not whether, but only where and when.