Andrei Sakharov helped develop the Soviet hydrogen bomb but urged its limitation.
He was a prominent 1970s dissident and won the 1975 Nobel Peace Prize.
In January 1980, after criticizing Soviet intervention in Afghanistan, Breshnev exiled him to Gorky.
Gorbachev allowed Sakharov and his wife Yelena Bonner's return to Moscow in December 1986.
Their apartment became a mecca for aid-seekers.
Sakharov supported Gorbachev's reforms but urged improvement in human rights and a nuclear testing ban.
In April 1989 he was elected to parliament after Soviet physicists voted secretly to nominate him.
Sakharov, 68, died in December 1989 of an apparent heart attack after urging creation of an opposition party.