Physicist Andrei D. Sakharov became the youngest member of the Soviet Academy of Sciences and helped develop the Soviet hydrogen bomb, but urged limiting its production and testing.
He was a prominent 1970s dissident and won the 1975 Nobel Peace Prize.
In January 1980, after Sakharov criticized Soviet intervention in Afghanistan, Breshnev exiled him to Gorky.
Gorbachev allowed Sakharov and his wife Yelena Bonner to return to Moscow in December 1986.
There they lived simply in a two-room, seventh-floor apartment which became a mecca for Soviets seeking aid.
Sakharov supported Gorbachev's reforms but called for speedier progress in human rights, political prisoner liberation, and a nuclear testing ban.
In November 1988 he visited the US, underwent medical tests, and promoted a world peace foundation.
In April 1989, he was elected to parliament after Soviet physicists voted secretly to nominate him.
He warned of national economic catastrophe.
Sakharov died alone in his Moscow apartment in December 1989 at the age of 68, of an apparent heart attack, hours after urging creation of an opposition party.
World and Soviet leaders and press eulogized him as a sincere man who suffered great injustice and helped change Soviet society.
45,000 grievers filed past Sakharov's body.
Sakharov had four children and four grandchildren.