The rate of tuberculosis, in decline for many years, rose again in the early nineties, largely due to the prevalence of AIDS, which destroys the body's ability to fight off the disease.
Inner cities were hard-hit, especially among black and Hispanic populations which had a high rate of AIDS.
Health officials recommended vigorous testing and treatment programs.
TB, they said, is treatable and treatment was recommended, especially in persons with AIDS.
Studies suggested that blacks are more susceptible to TB than whites.
TB, an airborne infection, was reportedly easily spread in poorly ventilated office buildings, airplanes, hospitals and prisons.
Internationally, Latvia reported a sizable increase in TB.