Tuberculosis (TB) is a highly contagious, but preventable and curable, bacterial lung disease.
About 7% of Americans carry the bacteria, but only about 10% develop an active infection.
In 1990, TB was killing 3 million people annually worldwide.
In 1993, cases and deaths increased in Latvia.
By 1990 the number of cases in the United States stopped declining.
AIDS patients, prisoners, the homeless, the undernourished, office workers, those with serious illnesses, and blacks are more susceptible.
To slow the spread, testing and treatment are needed for prisoners, the homeless, substance abusers, and AIDS patients.
Building ventilation needs to be improved.