U.S. military aircraft crashes are not uncommon.
In the period from June 1988 through April 1994 innumerable crashes have been reported world wide--two F-16 fighter jets near Bodenheim, Germany; an F-16C in a remote area of Iwate Prefecture in Japan; an A- 10 attack jet in Britain; a B-52 bomber in Michigan; a Navy F-14 fighter plunging into the Atlantic of Hatteras, North Carolina; five crashes within two months in Saudi Arabia; --and more.
Local and national press coverage is extensive when a crash occurs in or near a densely populated area.
In December 1988, a U.S. Air Force A-10 Thunderbolt crashed into a working class neighborhood of Remscheid, West Germany killing six people and severely injuring seven.
Even before this fatal crash, 12 major military aircraft accidents had killed 95 people that year alone in Germany, including 70 deaths at an air show accident at the U.S. airbase in Ramstein.
Ironically, this model aircraft has the safest flying record in the U.S. arsenal.
It experiences an accident rate of less than 4 Class A mishaps per 100,000 flying hours.
A Class A mishap is one in which there is either a fatality or damage to an aircraft exceeding $500,000.