Each year, tens of thousands of fires will burn hundreds of thousands of acres in national parklands and forests.
Lightening starts most of them; however, human carelessness and arsonists also cause many.
The National Park Service follows a controversial "natural burn" policy, which allows lightening-induced fires to burn themselves out, except where they threaten towns or park buildings.
When intervention is needed, it often cost millions of dollars for the thousands of people and the air tankers, guide planes, helicopters and bulldozers needed to fight the fires.
The cost of destroyed vehicles, homes, and structures, not to mention lost timber is also high.