South Korea 1979 A member of an investigation team, which probed the assassination of President Pak Chong-hui in October 1979, testified that the then Army Chief of Staff was not involved in the slaying.
Palestine 1989 The US has denied Yasser Arafat's accusation that the US was involved in the assassination of Khalil Wazir, PLO's second in command, and that the US is threatening to kill PLO officials.
Philippines 1989 Suspected communist rebels brutally killed Col. Herminio Taylo, the police chief of Makati.
Colombia 1990 A third presidential candidate, Carlos Pizarro, was assassinated by drug traffickers in Bogota, Colombia.
Egypt 1990 Iraqi agents or Egyptian Moslem Fundamentalists were blamed for the assassination of Rifaat el- Mahgoub, Egypt's second highest official.
India 1991 Former Prime Minister Rajiv Ghandi was assassinated on 22 May in Tamil Nadu.
Ghandi's Congress Party had many enemies; namely, hardened opponents in Tamil Nadu.
Lebanon 1994 Jordanian diplomat Na'ib al-Ma'ayitah was assassinated in Beirut on 29 January by the Fatah Revolutionary Council and a Jordanian fundamentalist organization.
Mexico 1994 Presidential candidate, Luis Donaldo Colosio Marrieta, was assassinated in March.
In October, Jose Francisco Ruiz Massieu, number two official of Mexico's ruling party, was assassinated by order of a federal deputy.