In September 1989, Category 4 Hurricane Hugo, with 135mph winds, damaged the eastern Caribbean then hit South Carolina, where coastal residents fled inland or into shelters.
17 Carolinians were killed.
Satellites, computers, and reconnaissance planes helped forecasters monitor Hugo's progress.
Insurance claims broke records.
The greenhouse effect could raise future storms' destructive power by 50%.