Flooding in Guangdong, Hunan, Jiangxi, Guangxi, Fujiang and Zhejiang provinces that followed after heavy June storms has subsided, but in Guangdong 200 people died and 1.2 million hectares of crops were ruined.
Fujiang also suffered substantial agricultural losses.
Wen Jiabo (CPC Central Committee Secretariat member) and other officials toured the flooded areas.
They praised the soldiers and civilians who battled the floods, saved key infrastructure and industrial resources and assisted victims.
The people were urged to concentrate on recovery efforts and actions to minimize economic losses.
Resumption of agricultural production in Jiangxi, one of China's major bread baskets, was of particular concern.