Miners throughout the world have used strikes not only to achieve economic gains, but to gain greater control over their industries and to achieve political ends.
Miners in Poland struck not only for higher wages, but also for the legalization of Solidarity and the reinstatement of workers fired for union activity.
They also wanted a clear restructuring strategy for their industry.
Coal miners throughout the Soviet Union struck for more local control of their industries as well as better living and working conditions.
The labor unrest was the Soviet Union's worst in 60 years.
Until Gorbachev rose to power in 1985, strikes were not tolerated.
Miners in Kazakhstan and the Ukraine demanded real sovereignty for the 15 Soviet republics as well as a law to allow private ownership of industry and land.
Coal miners in Romania, spearheaded violent anti-reform rampages and well as demand for increased wages.
In South Africa coal and gold miners were to begin a strike for higher wages and working conditions.
Coal and gold account for more than half of South Africa's foreign currency earnings.
In the United States coal miners in four states walked off the job in sympathy for miners in a bitter dispute with Pittston Coal Group.