The Indian government has been fighting Muslim insurgents in the state of Jammu- Kashmir for the last seven months.
More than 1,000 people have been killed.
India (predominately Hindu) and Pakistan (predominately Islamic) have fought two wars over Kashmir since the nations were established in 1947.
Jammu-Kashmir is 62 percent Muslim and the insurgents want an independent nation.
Violence is occurring primarily near Srinagar, the capital, and along the border with Pakistan.
India claims the insurgents are being trained and armed in Pakistan.
Pakistan denies these charges.
The two nations recently exchanged fire, but both say there is no cause for concern.