A violent storm spawned tornadoes and thunderstorms across the Midwest and South, then blew north knocking over a school cafeteria wall in upstate New York, killing seven children.
Altogether, fourteen states and Washington D.C. were affected.
The toll from the two-day storm is at least 27 dead and over 500 hundred injured.
Property damage is in the millions.
The worst damage by far was in Huntsville, Alabama where a tornado slammed into a shopping district, a residential area and a school, leaving at least 14 dead and injuring nearly 300.
The Governor called in State Troopers and the National Guard to assist.