In 1988, the United States suffered one of its worst droughts ever.
The Agriculture Department attempted to shore up meat prices with purchases.
Prices were depressed due to the drought-induced liquidation of herds.
It also allowed emergency haying and grazing in conservation and reserve acreage lands.
Congress then passed a record $3.9 billion drought relief bill, which helped thousands of farmers nationwide.
North Dakota, along with Iowa, Illinois, Minnesota and Wisconsin received nearly half of the allocated aid.
A 1990 study showed that because of high 1988 commodity prices there were no significant ill affects for farmers despite the drought.