In 1988, at least 29% of the nation was hit by a drought about equal to the one in 1911.
In August 1988, Reagan signed a $3.9 billion drought relief bill.
Grain production was predicted to be 31% below 1987.
The aid package did reduce loses and stave off bankruptcies in the drought ravaged states, but much of the money ended up in other hands.
A 1990 postmortem of the drought revealed that it was not as bad as it could have been.
Computer modeling suggested it was caused by ocean temperature abnormalities near the equator in the Pacific Ocean.